builds/urls.py
from django.urls import path
from builds import views

app_name = 'builds'

urlpatterns = [
  path('', views.home, name='builds')
]

contacts/urls.py
from django.urls import path
from contacts import views

app_name = 'contacts'
urlpatterns = [
    path('', views.home, name='contacts')
]

home/urls.py
from django.urls import path

from . import views

app_name ='home'

#Urls of app home
urlpatterns = [
  #path  -- view to render
    path('', views.home,name='home')
]

vercel_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('projects/', include('builds.urls')),
    path('contacts/', include('contacts.urls')),
]

builds/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models

# Create your models here.

builds/views.py
from django.shortcuts import render
# Create your views here.


def home(request):
    title = {'title':'contact'}
    return render(
        request,
        'builds/builds.html',
        title
        )

contacts/views.py
from django.shortcuts import render

def home(request):
  return render(request, 'home/contacts.html')

home/views.py
from django.shortcuts import render
# Create your views here.


def home(request):
    title = {'title':'Página inicial'}
    return render(
        request,
        'home/index.html',
        title
        )

builds/templates/builds/builds.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "builds/styles.css" %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "imgs/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "imgs/favicon-16x16.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "imgs/favicon-32x32.png" %}">
    <title>Projetos</title>
  </head>
  <body>
    <div class="main">
    <div class="stars">
    </div>
    <!-- Criando nosso cabealho -->
    <div class="header">
      <div class="clique">
        <div class="voltar">
          <h2><a href="{% url "home:home" %}"><</a></h2>
        </div>
        <div class="endpoints">
          <h2><a href="{% url "builds:builds" %}">Projetos</a></h2>
          <h2><a href="{% url "contacts:contacts" %}">contato</a></h2>
        </div>
      </div>
    </div>
    <!-- Fim do cabeçalho -->
    <div class="text-project">
      <h2>Projetos</h2>
      <p>Projetos relevantes</p>
    </div>


    <!-- Começo dos projetos -->
    {% comment %} Início Projeto blog {% endcomment %}
      <a href="https://fortalballers.vercel.app" target="_blank">
        <div class="projetos">
          <div class="projeto">
            <h3>FortalBallers (FLASK, PYTHON , HTML , CSS, JS)</h3>
            <img src="{% static "imgs/fortal.jpg" %}" alt="img-FortalBallers">
          </div>
      </a>
    {% comment %} Fim projeto blog {% endcomment %}

      {% comment %} Começo landing page {% endcomment %}
      <a href="https://landing-jack.netlify.app/" target="_blank">
        <div class="projeto">
          <h3>Landing-Page (HTML , CSS , JS)</h3>
          <img src="{% static "imgs/land.jpg" %}" alt="site-landing-page">
        </div>
      </a>
      {% comment %} Fim projeto landing page {% endcomment %}

      {% comment %} Começo projeto encurtador {% endcomment %}
      <a target="_blank" href="https://encurtador-simples.vercel.app/" >
          <div class="projeto">
            <h3>Encurtador (HTML , CSS)</h3>
            <img src="{% static "imgs/encurtador.jpg" %}" alt="site-encurtador">
        </div>
      </a>
      {% comment %} Fim projeto encurtador {% endcomment %}

      {% comment %} Começo projeto cópia Netflix {% endcomment %}
      <a href="https://netflixcop.vercel.app/" target="_blank">
        <div class="projeto">
          <h3>Clone Netflix</h3>
          <img src="{% static "imgs/netflix.jpg" %}" alt="site-clone-netflix">
        </div>
      </a>
      {% comment %} Fim projeto cópia Netflix {% endcomment %}

      {% comment %} Começo projeto cópia Netflix {% endcomment %}
      <a href="https://pinguim-css.vercel.app/" target="_blank">
        <div class="projeto">
          <h3>Pinguim (HTML, CSS)</h3>
          <img src="{% static "imgs/pinguim.jpg" %}" alt="site-penguim">
        </div>
      </a>
      {% comment %} Fim projeto cópia Netflix {% endcomment %}
      {% comment %} FIM DOS PROJETOS{% endcomment %}
      <!-- <div class="hr"></div> -->

    </div>
    <footer>
      <p>
        <a target="_blank" href="https://encurtador-simples.vercel.app/"
          >Feito com <span class="heart">❤</span> por Jack</a>
      </p>
    </footer>
    </div>
      <script src="{% static 'js/index.js' %}"></script>
    
  </body>
</html>

contacts/templates/home/contacts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static "contacts/styles.css" %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static "imgs/apple-touch-icon.png" %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static "imgs/favicon-16x16.png" %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static "imgs/favicon-32x32.png" %}">
  <title>Contatos</title>
</head>
<body>
  <div class="header">
    <div class="clique">
      <div class="voltar">
        <h2><a href="{% url "home:home" %}"><</a></h2>
      </div>
      <div class="endpoints">
        <h2><a href="{% url "builds:builds" %}">Projects</a></h2>
        <h2><a href="{% url "contacts:contacts" %}">contact</a></h2>
      </div>
    </div>
  </div>
  <div class="main">
    <a href="https://www.linkedin.com/in/jackson-nascimento-bb4454205/" alt="linkedin">
      <div class="card">
        <img src="{% static "imgs/link.png" %}" alt="foto-linkedin">
        <h2>
          Linkedin
        </h2>
      </div>
    </a>

    <a href="https://www.instagram.com/imdevjack/" alt="icone-instagram">
      <div class="card">
        <img src="{% static "imgs/instagram.png" %}" alt="instagram">
        <h2>
            Email
        </h2>
      </div>
    </a>

  <a href="https://github.com/JackDev085">
    <div class="card">
      <img src="{% static "imgs/github.png" %}" alt="">
      <h2>
       Github
      </h2>
    </div>
  </a>
  </div>
  <footer>
    <p>
      <a target="_blank" href="https://encurtador-simples.vercel.app/"
        >Feito com <span class="heart">❤</span> por Jack</a>
    </p>
  </footer>
</body>
</html>

home/templates/home/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel='stylesheet' href="{% static 'home/styles.css' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static "imgs/apple-touch-icon.png" %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static "imgs/favicon-16x16.png" %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static "imgs/favicon-32x32.png" %}">
  <link rel="manifest" href="/site.webmanifest">
  <title>Página inicial</title>
</head>
<body>
  
  <main class="main">
    <span class="stars"></span>
    <div class="top">
      <h2>
        <a href="{% url "builds:builds" %}">projetos</a>
      </h2>
      <h2>
        <a href="{% url "contacts:contacts" %}">contatos</a>
      </h2>
    </div>
    <div class="name">
      <h1>jackson lorran</h1>
    </div>
    <div class="bottom">
      <h2>Desenvolvedor Web</h2>
    </div>
  </main>
  <script src="{% static 'js/index.js' %}"></script>
</body>
</html>